<?php

namespace CLAList\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SkyboxRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SkyboxRepository extends EntityRepository
{
}
